"""db

Revision ID: 1c4ad2c7942e
Revises: ec7107ac5e0c
Create Date: 2023-08-24 20:29:48.600356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c4ad2c7942e'
down_revision = 'ec7107ac5e0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kiwi_l4', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kiwi_l4', 'date')
    # ### end Alembic commands ###
