"""init 1

Revision ID: 4886a04e63f9
Revises: d5605cc5ab4d
Create Date: 2023-01-14 15:55:48.593252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4886a04e63f9'
down_revision = 'd5605cc5ab4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mms_deep',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_rate_currency_total_price_offer', sa.String(length=256), nullable=True),
    sa.Column('data_rate_currency_night_price_offer', sa.String(length=256), nullable=True),
    sa.Column('data_rate_currency_total_price_original', sa.String(length=256), nullable=True),
    sa.Column('data_rate_currency_night_price_original', sa.String(length=256), nullable=True),
    sa.Column('data_rate_inc_total_price_offer', sa.String(length=256), nullable=True),
    sa.Column('data_rate_inc_night_price_offer', sa.String(length=256), nullable=True),
    sa.Column('data_rate_inc_total_price_original', sa.String(length=256), nullable=True),
    sa.Column('data_rate_inc_night_price_original', sa.String(length=256), nullable=True),
    sa.Column('data_rate_ex_total_price_offer', sa.String(length=256), nullable=True),
    sa.Column('data_rate_ex_night_price_offer', sa.String(length=256), nullable=True),
    sa.Column('data_rate_ex_total_price_original', sa.String(length=256), nullable=True),
    sa.Column('data_rate_ex_night_price_original', sa.String(length=256), nullable=True),
    sa.Column('display_night_price_offer', sa.String(length=256), nullable=True),
    sa.Column('display_night_price_original', sa.String(length=256), nullable=True),
    sa.Column('display_total_price_offer', sa.String(length=256), nullable=True),
    sa.Column('display_total_price_original', sa.String(length=256), nullable=True),
    sa.Column('is_offer', sa.Boolean(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.Column('room_info_raw', sa.String(length=256), nullable=True),
    sa.Column('board_raw', sa.String(length=256), nullable=True),
    sa.Column('hotel_name', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('from', sa.DateTime(), nullable=True),
    sa.Column('to', sa.DateTime(), nullable=True),
    sa.Column('top_name', sa.String(length=256), nullable=True),
    sa.Column('top_id', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mms_lite',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_id', sa.String(length=256), nullable=True),
    sa.Column('data_lat', sa.String(length=256), nullable=True),
    sa.Column('data_long', sa.String(length=256), nullable=True),
    sa.Column('data_name', sa.String(length=256), nullable=True),
    sa.Column('data_prop', sa.String(length=256), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('country', sa.String(length=256), nullable=True),
    sa.Column('data_rate_currency', sa.String(length=256), nullable=True),
    sa.Column('data_rate_ex', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('data_rate_inc', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('from', sa.DateTime(), nullable=True),
    sa.Column('to', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mms_lite')
    op.drop_table('mms_deep')
    op.drop_table('api')
    # ### end Alembic commands ###
