"""db

Revision ID: 68f687d377d3
Revises: 0cbc8b001863
Create Date: 2023-08-30 09:00:29.810790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f687d377d3'
down_revision = '0cbc8b001863'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtuoso_l2', sa.Column('supplier_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtuoso_l2', 'supplier_id')
    # ### end Alembic commands ###
