"""db

Revision ID: 8200198353d9
Revises: 1c4ad2c7942e
Create Date: 2023-08-24 20:59:10.880858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8200198353d9'
down_revision = '1c4ad2c7942e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtuoso_l2', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('virtuoso_l2', sa.Column('end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtuoso_l2', 'end_date')
    op.drop_column('virtuoso_l2', 'start_date')
    # ### end Alembic commands ###
