"""db 1

Revision ID: 96150575284a
Revises: 3b16d36a106f
Create Date: 2023-01-15 15:51:41.857128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96150575284a'
down_revision = '3b16d36a106f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
