"""db 2

Revision ID: 98bb13999fe0
Revises: 96150575284a
Create Date: 2023-01-15 15:56:44.088766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98bb13999fe0'
down_revision = '96150575284a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mms_deep', 'room_info_raw',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('mms_deep', 'board_raw',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('mms_deep', 'hotel_name',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=1024),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mms_deep', 'hotel_name',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    op.alter_column('mms_deep', 'board_raw',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    op.alter_column('mms_deep', 'room_info_raw',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###
